/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.controls.TwinkleAnimation;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LedsBetter extends SubsystemBase {
    private final CANBus kCANBus = new CANBus("Bobby");
    private final CANdle m_candle = new CANdle(7, kCANBus);

    private final TwinkleAnimation m_slot0Animation = new TwinkleAnimation(8, 50)
            .withSlot(0)
            .withColor(new RGBWColor(255, 0, 0, 0))
            .withMaxLEDsOnProportion(0.5)
            .withFrameRate(Hertz.of(100));

    private final TwinkleAnimation m_slot1Animation = new TwinkleAnimation(51, 125)
            .withSlot(1)
            .withColor(new RGBWColor(1, 155, 2, 0))
            .withMaxLEDsOnProportion(0.5)
            .withFrameRate(Hertz.of(100));

    private final TwinkleAnimation m_slot2Animation = new TwinkleAnimation(126, 200)
            .withSlot(2)
            .withColor(new RGBWColor(255, 0, 0, 0))
            .withMaxLEDsOnProportion(0.5)
            .withFrameRate(Hertz.of(100));

    private final SolidColor[] m_colors = new SolidColor[] {};

    public LedsBetter() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
                    for (var solidColor : m_colors) {
                        m_candle.setControl(solidColor);
                    }
                    m_candle.setControl(m_slot0Animation);
                    m_candle.setControl(m_slot1Animation);
                    m_candle.setControl(m_slot2Animation);
                })
                .ignoringDisable(true);
    }
}
